version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: desafioiliapw
      POSTGRES_DB: desafioilia
