version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: desafioiliapw
      POSTGRES_DB: desafioilia2
  app:
    image: node:12-alpine
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: >
      sh -c "npm install && npm run migrate && npm run seed && npm run dev"
