exports.seed = function (knex) {
  return knex('movies').insert([
    {
      adult: false,
      backdrop_path: '/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg',
      budget: 63000000,
      homepage: '',
      imdb_id: 'tt0137523',
      original_language: 'en',
      original_title: 'Fight Club',
      overview:
        'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
      popularity: 0.5,
      poster_path: null,
      release_date: '1999-10-12',
      revenue: 100853753,
      runtime: 139,
      status: 'Released',
      tagline: "How much can you know about yourself if you've never been in a fight?",
      title: 'Fight Club',
      video: false,
      vote_average: 7.8,
      vote_count: 3439,
    },
    {
      adult: false,
      backdrop_path: '/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg',
      budget: 63000000,
      homepage: '',
      imdb_id: 'tt0137523',
      original_language: 'en',
      original_title: 'Fight Club',
      overview:
        'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
      popularity: 0.5,
      poster_path: null,
      release_date: '1999-10-12',
      revenue: 100853753,
      runtime: 139,
      status: 'Released',
      tagline: "How much can you know about yourself if you've never been in a fight?",
      title: 'Fight Club',
      video: false,
      vote_average: 7.8,
      vote_count: 3439,
    },
  ]);
};
